#!/usr/bin/env node
// WeftCut site — sitemap generator.
//
// Exists for one field: <lastmod>. Google and Bing both ignore <changefreq> and
// <priority> outright (and have said so publicly), so the hand-maintained
// sitemap they replaced was carrying two dead fields and no live one. lastmod is
// the only signal in the format that still moves a crawler, and it is the one
// thing a static file can't keep honest on its own.
//
// The date comes from git: the last commit that touched the page's own HTML.
// Not the CSS, not the JS — a restyle is not a content change, and a lastmod
// that moves when the copy didn't is exactly what makes a crawler stop trusting
// the field. Uncommitted edits to the page stamp today instead, so the sitemap
// tells the truth about a deploy from a dirty tree.
//
// Granularity is deliberately a date, not a timestamp: it's all the precision
// this claim deserves, and it keeps the output idempotent within a day, so
// --check doesn't fail on a re-run that changed nothing.
//
//   node build-sitemap.mjs            # generate
//   node build-sitemap.mjs --check    # verify the committed output is current
import { spawnSync } from 'node:child_process'
import { existsSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = dirname(fileURLToPath(import.meta.url))
const OUT = join(ROOT, 'sitemap.xml')
const CHECK = process.argv.includes('--check')

const ORIGIN = 'https://weftcut.com'

// Every indexable URL and the file whose history dates it. The Markdown twins
// are deliberately absent: same content at the same URL under negotiation,
// already declared via rel="alternate", and listing them would read as
// duplicate content rather than as two views of one page.
const PAGES = [
  { loc: `${ORIGIN}/`, source: 'index.html' },
  { loc: `${ORIGIN}/zh/`, source: 'zh/index.html' },
]

// hreflang is mirrored from the pages' own <link rel="alternate"> set: every
// URL declares the whole set including itself, x-default points at English.
const ALTERNATES = [
  { hreflang: 'en', href: `${ORIGIN}/` },
  { hreflang: 'zh-Hans', href: `${ORIGIN}/zh/` },
  { hreflang: 'x-default', href: `${ORIGIN}/` },
]

const git = (...args) => {
  const { status, stdout } = spawnSync('git', args, { cwd: ROOT, encoding: 'utf8' })
  return status === 0 ? stdout.trim() : null
}

const asDate = (iso) => iso.slice(0, 10)

/** Last content change for one page, as YYYY-MM-DD. */
function lastmod(source) {
  const path = join(ROOT, source)
  if (!existsSync(path)) throw new Error(`sitemap: missing source ${source}`)

  // Dirty working tree wins: whatever is about to deploy is newer than the
  // commit it came from. `git status --porcelain` prints nothing for a clean
  // file, which is the whole test.
  const dirty = git('status', '--porcelain', '--', source)
  if (dirty) return asDate(new Date().toISOString())

  const committed = git('log', '-1', '--format=%cI', '--', source)
  if (committed) return asDate(committed)

  // No git (a tarball, a fresh CI checkout with no history): mtime is the only
  // date left, and it beats emitting no lastmod at all.
  return asDate(statSync(path).mtime.toISOString())
}

const xml = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<!-- Generated by build-sitemap.mjs — do not edit by hand. -->',
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
  '        xmlns:xhtml="http://www.w3.org/1999/xhtml">',
  ...PAGES.map(({ loc, source }) =>
    [
      '  <url>',
      `    <loc>${loc}</loc>`,
      ...ALTERNATES.map(
        ({ hreflang, href }) =>
          `    <xhtml:link rel="alternate" hreflang="${hreflang}" href="${href}"/>`
      ),
      `    <lastmod>${lastmod(source)}</lastmod>`,
      '  </url>',
    ].join('\n')
  ),
  '</urlset>',
  '',
].join('\n')

if (CHECK) {
  const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : null
  if (current !== xml) {
    console.error('✗ sitemap.xml is stale — run `node build-sitemap.mjs`')
    process.exit(1)
  }
  console.log('✓ sitemap.xml is current')
} else {
  writeFileSync(OUT, xml)
  console.log(`✓ wrote sitemap.xml (${PAGES.length} URLs)`)
  for (const { loc, source } of PAGES) console.log(`  ${loc} — ${lastmod(source)}`)
}
