#!/usr/bin/env node
// WeftCut site — sitemap generator.
//
// Exists for one field: <lastmod>. Google and Bing both ignore <changefreq> and
// <priority> outright (and have said so publicly), so the hand-maintained
// sitemap they replaced was carrying two dead fields and no live one. lastmod is
// the only signal in the format that still moves a crawler, and it is the one
// thing a static file can't keep honest on its own.
//
// The date comes from git: the last commit that touched the page's own HTML.
// Not the CSS, not the JS — a restyle is not a content change, and a lastmod
// that moves when the copy didn't is exactly what makes a crawler stop trusting
// the field. Uncommitted edits to the page stamp today instead, so the sitemap
// tells the truth about a deploy from a dirty tree.
//
// Granularity is deliberately a date, not a timestamp: it's all the precision
// this claim deserves, and it keeps the output idempotent within a day, so
// --check doesn't fail on a re-run that changed nothing.
//
//   node build-sitemap.mjs            # generate
//   node build-sitemap.mjs --check    # verify the committed output is current
import { spawnSync } from 'node:child_process'
import { existsSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = dirname(fileURLToPath(import.meta.url))
const OUT = join(ROOT, 'sitemap.xml')
const CHECK = process.argv.includes('--check')

const ORIGIN = 'https://weftcut.com'

// Every indexable URL and the file whose history dates it. The Markdown twins
// are deliberately absent: same content at the same URL under negotiation,
// already declared via rel="alternate", and listing them would read as
// duplicate content rather than as two views of one page.
//
// The empty slug is the homepage; the rest are build-pages.mjs's documentary
// pages, which exist in both languages under the same path.
const SLUGS = ['', 'mcp', 'ai-video-editor', 'motifs']

// hreflang is mirrored from each page's own <link rel="alternate"> set: a URL
// declares the whole group it belongs to, itself included, and x-default points
// at English. Crucially the group is PER PAGE — /mcp/ must point at /zh/mcp/,
// not at the homepage, or the annotation is worse than absent.
//
// lastmod dates a generated page by the Markdown it was built from, not by the
// HTML: re-running the generator is not a content change, and a lastmod that
// moves when the copy didn't is what makes a crawler stop trusting the field.
const PAGES = SLUGS.flatMap((slug) => {
  const tail = slug ? `${slug}/` : ''
  const en = `${ORIGIN}/${tail}`
  const zh = `${ORIGIN}/zh/${tail}`
  const alternates = [
    { hreflang: 'en', href: en },
    { hreflang: 'zh-Hans', href: zh },
    { hreflang: 'x-default', href: en },
  ]
  return [
    { loc: en, source: slug ? `pages/${slug}.en.md` : 'index.html', alternates },
    { loc: zh, source: slug ? `pages/${slug}.zh.md` : 'zh/index.html', alternates },
  ]
})

const git = (...args) => {
  const { status, stdout } = spawnSync('git', args, { cwd: ROOT, encoding: 'utf8' })
  return status === 0 ? stdout.trim() : null
}

// Normalize git's offset timestamps to UTC, as the dirty-tree clock and file
// mtimes already are. Committing a page must not change its calendar date.
const asDate = (iso) => new Date(iso).toISOString().slice(0, 10)

/** Last content change for one page, as YYYY-MM-DD. */
function lastmod(source) {
  const path = join(ROOT, source)
  if (!existsSync(path)) throw new Error(`sitemap: missing source ${source}`)

  // Dirty working tree wins: whatever is about to deploy is newer than the
  // commit it came from. `git status --porcelain` prints nothing for a clean
  // file, which is the whole test.
  const dirty = git('status', '--porcelain', '--', source)
  if (dirty) return asDate(new Date().toISOString())

  const committed = git('log', '-1', '--format=%cI', '--', source)
  if (committed) return asDate(committed)

  // No git (a tarball, a fresh CI checkout with no history): mtime is the only
  // date left, and it beats emitting no lastmod at all.
  return asDate(statSync(path).mtime.toISOString())
}

const xml = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<!-- Generated by build-sitemap.mjs — do not edit by hand. -->',
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
  '        xmlns:xhtml="http://www.w3.org/1999/xhtml">',
  ...PAGES.map(({ loc, source, alternates }) =>
    [
      '  <url>',
      `    <loc>${loc}</loc>`,
      ...alternates.map(
        ({ hreflang, href }) =>
          `    <xhtml:link rel="alternate" hreflang="${hreflang}" href="${href}"/>`
      ),
      `    <lastmod>${lastmod(source)}</lastmod>`,
      '  </url>',
    ].join('\n')
  ),
  '</urlset>',
  '',
].join('\n')

if (CHECK) {
  const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : null
  if (current !== xml) {
    console.error('✗ sitemap.xml is stale — run `node build-sitemap.mjs`')
    process.exit(1)
  }
  console.log('✓ sitemap.xml is current')
} else {
  writeFileSync(OUT, xml)
  console.log(`✓ wrote sitemap.xml (${PAGES.length} URLs)`)
  for (const { loc, source } of PAGES) console.log(`  ${loc} — ${lastmod(source)}`)
}
