#!/usr/bin/env node
// WeftCut site — deploy bundle assembler.
//
// The repo root doubles as the site root, which is exactly what makes
// `npm start` work with no build step — and exactly the wrong thing to hand a
// CDN. `.work/` alone is 130 MB of raw captures, and README.md / CONTENT.md are
// working notes that shouldn't answer a public GET. So dist/ is assembled from
// an explicit allowlist rather than filtered out of the repo: a new file has to
// be named here before it can reach production.
//
// The copy is followed by a link check — every root-absolute URL the shipped
// HTML/CSS/JS references has to resolve inside dist/. That is what keeps a
// short allowlist safe: forget an entry and this fails naming the missing file,
// instead of publishing a page with a hole in it.
//
//   node build-dist.mjs
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = dirname(fileURLToPath(import.meta.url))
const DIST = join(ROOT, 'dist')

// Everything the site serves, and nothing else. `zh/` is generated by
// build-i18n.mjs; `_headers` is read by Cloudflare, never by the browser.
const SHIP = [
  'index.html',
  'index.css',
  'index.js',
  'index.md',
  'zh',
  'assets',
  '.well-known',
  '_headers',
  'llms.txt',
  'robots.txt',
  'sitemap.xml',
]

// worker.js is deliberately absent: wrangler loads it from the repo root as the
// deploy's `main`. Copying it into dist/ would also publish it as a fetchable
// static file at /worker.js.

// Root-absolute URLs are the only kind the site uses in markup, so these three
// shapes cover every local reference on the page. An external https:// URL is
// not this build's problem and deliberately doesn't match.
//
// The exception is our own origin, spelled out in full: og:image, canonical and
// hreflang have to be absolute to be worth anything, which would otherwise put
// the share cards — the one asset no visitor ever loads, so no one would notice
// it 404ing — outside the only check that would catch a typo.
const REFERENCES = [
  /(?:src|href|poster)="(\/[^"]*)"/g, // markup
  /url\(\s*["']?(\/[^"')]+)["']?\s*\)/g, // css
  /fetch\(\s*["'](\/[^"']+)["']/g, // js
  /https:\/\/weftcut\.com(\/[^"']*)/g, // our own origin, written out
]

const problems = []

const walk = (dir) =>
  readdirSync(dir, { withFileTypes: true }).flatMap((e) =>
    e.isDirectory() ? walk(join(dir, e.name)) : [join(dir, e.name)]
  )

// --- copy -------------------------------------------------------------------
rmSync(DIST, { recursive: true, force: true })
mkdirSync(DIST, { recursive: true })
for (const entry of SHIP) {
  const from = join(ROOT, entry)
  if (!existsSync(from)) {
    problems.push(`missing source: ${entry}`)
    continue
  }
  cpSync(from, join(DIST, entry), { recursive: true })
}

if (problems.length) {
  console.error(`✗ dist: ${problems.length} problem(s)`)
  for (const p of problems) console.error('   ' + p)
  process.exit(1)
}

// --- link check ---------------------------------------------------------------
const files = walk(DIST)
const checked = new Set()

for (const file of files.filter((f) => /\.(html|css|js)$/.test(f))) {
  const label = file.slice(DIST.length + 1).replaceAll('\\', '/')
  const text = readFileSync(file, 'utf8')
  for (const re of REFERENCES) {
    for (const [, raw] of text.matchAll(re)) {
      // A directory URL resolves to its index.html — that's how `/zh/` works.
      const url = raw.split(/[?#]/)[0]
      const target = url.endsWith('/') ? url + 'index.html' : url
      checked.add(target)
      if (!existsSync(join(DIST, target))) problems.push(`${label}: dead link ${raw}`)
    }
  }
}

if (problems.length) {
  console.error(`✗ dist: ${problems.length} dead link(s)`)
  for (const p of problems) console.error('   ' + p)
  process.exit(1)
}

// --- JSON-LD ------------------------------------------------------------------
// A trailing comma in a ld+json block is invisible everywhere that matters: the
// page renders, the tests pass, and the structured data silently doesn't exist
// as far as a crawler is concerned. Parsing it here is the only cheap way to
// find out before deploying. Each block must also name a @type — an untyped
// node is valid JSON and worth nothing.
for (const file of files.filter((f) => f.endsWith('.html'))) {
  const label = file.slice(DIST.length + 1).replaceAll('\\', '/')
  const html = readFileSync(file, 'utf8')
  const blocks = [...html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)]
  if (!blocks.length) problems.push(`${label}: no JSON-LD`)
  for (const [index, [, raw]] of blocks.entries()) {
    try {
      const node = JSON.parse(raw)
      if (!node['@type']) problems.push(`${label}: JSON-LD block ${index + 1} has no @type`)
    } catch (error) {
      problems.push(`${label}: JSON-LD block ${index + 1} is not valid JSON — ${error.message}`)
    }
  }
}

// --- agent-skill digests ------------------------------------------------------
// The discovery index publishes a sha256 for every skill so a client can prove
// it got the bytes the site meant to serve. That promise is only worth anything
// if the digest is checked here — edit a SKILL.md, forget the index, and the
// hash silently stops matching for everyone downstream.
const SKILLS = join(DIST, '.well-known', 'agent-skills', 'index.json')
if (existsSync(SKILLS)) {
  const index = JSON.parse(readFileSync(SKILLS, 'utf8'))
  for (const skill of index.skills ?? []) {
    const path = new URL(skill.url, 'https://weftcut.com').pathname
    const file = join(DIST, path)
    if (!existsSync(file)) {
      problems.push(`agent-skills: ${skill.name} points at missing ${path}`)
      continue
    }
    const actual = 'sha256:' + createHash('sha256').update(readFileSync(file)).digest('hex')
    if (actual !== skill.digest) {
      problems.push(
        `agent-skills: ${skill.name} digest is stale\n     index.json: ${skill.digest}\n     ${path}: ${actual}`
      )
    }
  }
}

if (problems.length) {
  console.error(`✗ dist: ${problems.length} problem(s)`)
  for (const p of problems) console.error('   ' + p)
  process.exit(1)
}

const bytes = files.reduce((n, f) => n + statSync(f).size, 0)
console.log(`✓ dist/ — ${files.length} files, ${(bytes / 1024 / 1024).toFixed(1)} MB`)
console.log(`  ${checked.size} local references resolved`)
