#!/usr/bin/env node
// WeftCut site — deploy bundle assembler.
//
// The repo root doubles as the site root, which is exactly what makes
// `npm start` work with no build step — and exactly the wrong thing to hand a
// CDN. `.work/` alone is 130 MB of raw captures, and README.md / CONTENT.md are
// working notes that shouldn't answer a public GET. So dist/ is assembled from
// an explicit allowlist rather than filtered out of the repo: a new file has to
// be named here before it can reach production.
//
// The copy is followed by a link check — every root-absolute URL the shipped
// HTML/CSS/JS references has to resolve inside dist/. That is what keeps a
// short allowlist safe: forget an entry and this fails naming the missing file,
// instead of publishing a page with a hole in it.
//
//   node build-dist.mjs
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = dirname(fileURLToPath(import.meta.url))
const DIST = join(ROOT, 'dist')

// Everything the site serves, and nothing else. `zh/` is generated by
// build-i18n.mjs; `_headers` is read by Cloudflare, never by the browser.
const SHIP = [
  'index.html',
  'index.css',
  'index.js',
  'zh',
  'assets',
  '_headers',
  'llms.txt',
  'robots.txt',
  'sitemap.xml',
]

// Root-absolute URLs are the only kind the site uses, so these three shapes
// cover every local reference on the page. An external https:// URL is not this
// build's problem and deliberately doesn't match.
const REFERENCES = [
  /(?:src|href|poster)="(\/[^"]*)"/g, // markup
  /url\(\s*["']?(\/[^"')]+)["']?\s*\)/g, // css
  /fetch\(\s*["'](\/[^"']+)["']/g, // js
]

const problems = []

const walk = (dir) =>
  readdirSync(dir, { withFileTypes: true }).flatMap((e) =>
    e.isDirectory() ? walk(join(dir, e.name)) : [join(dir, e.name)]
  )

// --- copy -------------------------------------------------------------------
rmSync(DIST, { recursive: true, force: true })
mkdirSync(DIST, { recursive: true })
for (const entry of SHIP) {
  const from = join(ROOT, entry)
  if (!existsSync(from)) {
    problems.push(`missing source: ${entry}`)
    continue
  }
  cpSync(from, join(DIST, entry), { recursive: true })
}

if (problems.length) {
  console.error(`✗ dist: ${problems.length} problem(s)`)
  for (const p of problems) console.error('   ' + p)
  process.exit(1)
}

// --- link check ---------------------------------------------------------------
const files = walk(DIST)
const checked = new Set()

for (const file of files.filter((f) => /\.(html|css|js)$/.test(f))) {
  const label = file.slice(DIST.length + 1).replaceAll('\\', '/')
  const text = readFileSync(file, 'utf8')
  for (const re of REFERENCES) {
    for (const [, raw] of text.matchAll(re)) {
      // A directory URL resolves to its index.html — that's how `/zh/` works.
      const url = raw.split(/[?#]/)[0]
      const target = url.endsWith('/') ? url + 'index.html' : url
      checked.add(target)
      if (!existsSync(join(DIST, target))) problems.push(`${label}: dead link ${raw}`)
    }
  }
}

if (problems.length) {
  console.error(`✗ dist: ${problems.length} dead link(s)`)
  for (const p of problems) console.error('   ' + p)
  process.exit(1)
}

const bytes = files.reduce((n, f) => n + statSync(f).size, 0)
console.log(`✓ dist/ — ${files.length} files, ${(bytes / 1024 / 1024).toFixed(1)} MB`)
console.log(`  ${checked.size} local references resolved`)
